name: BSides Montreal 2023

on: workflow_dispatch

jobs:
  hello-world:
    runs-on: ubtuntu-latest
    steps:
      - run: echo "Hello BSides Montreal 2023!"
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://juice-shop.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
